logging:
  level:
    org:
      springframework:
        cloud:
          netflix:
            zuul: trace
server:
  port: 9000
spring:
  application:
    name: api-zuul
  sleuth:
    enabled: true
    sampler:
      rate: 1
zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    account-service:
      path: /accounts/**
      service-id: account-service
    customer-service:
      path: /customers/**
      service-id: customer-service
    transaction-service:
      path: /transactions/**
      service-id: transaction-service
